version: '3'

services:
  url-shortener:
    container_name: url-shortener
    image: url-shortener:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env